[project]
name = "pandas-ch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "clickhouse-connect[arrow]>=0.13.0",
    "pandas>=3.0.1",
    "pandera[pandas]>=0.31.1",
    "pyinstaller>=6.21.0",
    "python-calamine>=0.6.2",
    "sqlalchemy>=2.0.49",
    "tkcalendar>=1.6.1",
    "toml>=0.10.2",
    "xlsxwriter>=3.2.9",
]
